version: '3.4'

services:
  backend:
    build:
      target: prod

  frontend:
    build:
      target: prod

  workers:
    build:
      context: workers/
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    userns_mode: "host"

  redis:
    image: redis:5.0.3

  db:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=etrdatabase

volumes:
  pg_data: {}
  pg_backups: {}
