# Generated by Django 2.1.5 on 2019-02-05 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rendering.models
import rendering.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.FileField(blank=True, null=True, storage=rendering.storage.OverwriteStorage(), upload_to=rendering.models.Module.module_path)),
                ('time', models.DateTimeField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True)),
                ('last_scene', models.CharField(blank=True, max_length=100, null=True)),
                ('last_project', models.CharField(blank=True, max_length=100, null=True)),
                ('last_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='rendering.Module')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('owner', 'project', 'source')},
        ),
    ]
