# Generated by Django 2.1.5 on 2019-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendering', '0004_auto_20190505_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
